### A Pluto.jl notebook ###
# v0.19.40

using Markdown
using InteractiveUtils

# ╔═╡ 8e9a3c40-9c6a-11ed-1f4e-7d1c8f4a9b2c
begin
    using Pkg
    Pkg.activate(joinpath(@__DIR__, ".."))
    using CairoMakie
    using Trixi
    using Statistics
end

# ╔═╡ 1a2b3c4d-9c6a-11ed-2f5e-8d2c9f5a0b3d
md"""
# 01. Mesh Visualization

Visualization of spectral element mesh and fault geometry.

This notebook loads and visualizes unstructured quadrilateral meshes generated for SEAS-SEME earthquake cycle simulations.

## Features
- Plot mesh structure with element boundaries
- Visualize boundary regions (fault, creep, absorbing, free surface)
- Show element refinement zones
- Display mesh statistics
"""

# ╔═╡ 2b3c4d5e-9c6a-11ed-3f6e-9d3c0f6a1c4e
md"""
## Load Mesh File

Specify the path to your mesh file (`.mesh` file generated by HOHQMesh):
"""

# ╔═╡ 3c4d5e6f-9c6a-11ed-4f7e-0d4c1f7a2d5f
mesh_file = "../data/mesh/dipping_fault_120/dipping_fault.mesh"

# ╔═╡ 4d5e6f70-9c6a-11ed-5f8e-1d5c2f8a3e60
mesh = isfile(mesh_file) ? UnstructuredMesh2D(mesh_file) : nothing

# ╔═╡ 5e6f7080-9c6a-11ed-6f9e-2e6c3f9a4f70
md"""
## Mesh Structure Visualization

Full mesh showing element boundaries and boundary regions.
"""

# ╔═╡ 6f708090-9c6a-11ed-7f0e-3f7c4f0a5880
if isfile(mesh_file)
    begin
        fig = Figure(resolution=(1000, 800))
        ax = Axis(fig[1, 1],
            xlabel="X (m)",
            ylabel="Y (m)",
            title="Unstructured Mesh - Element Boundaries",
            aspect=DataAspect()
        )

        # Plot all elements
        for el in 1:mesh.n_elements
            # Get corner coordinates for this element
            corners = mesh.corners[:, mesh.element_node_ids[:, el]]

            # Close the polygon
            x_coords = [corners[1, :]; corners[1, 1]]
            y_coords = [corners[2, :]; corners[2, 1]]

            # Plot element boundary
            lines!(ax, x_coords, y_coords, color=:black, linewidth=0.5)
        end

        # Highlight boundaries by color
        boundary_colors = Dict(
            "fault" => :red,
            "creep" => :orange,
            "absorbing" => :blue,
            "free_surface" => :green
        )

        # Plot boundary edges with colors
        for (boundary_name, color) in boundary_colors
            # Find boundary ID
            boundary_id = findfirst(==(boundary_name), mesh.boundary_names)
            if !isnothing(boundary_id)
                # Get boundary elements
                for boundary_elem in 1:size(mesh.boundary_node_ids, 2)
                    if mesh.boundary_names[mesh.boundary_node_ids[3, boundary_elem]] == boundary_name
                        node1 = mesh.boundary_node_ids[1, boundary_elem]
                        node2 = mesh.boundary_node_ids[2, boundary_elem]

                        x = [mesh.corners[1, node1], mesh.corners[1, node2]]
                        y = [mesh.corners[2, node1], mesh.corners[2, node2]]

                        lines!(ax, x, y, color=color, linewidth=3, label=boundary_name)
                    end
                end
            end
        end

        # Add legend
        # Legend(fig[1, 2], ax, "Boundaries", framevisible=true)

        fig
    end
end

# ╔═╡ 7080a0b0-9c6a-11ed-8f1e-4f8c5f1a6990
md"""
## Element Size Distribution

Shows the element size (area) distribution across the mesh. Smaller elements appear in the fault refinement zone.
"""

# ╔═╡ 80a0b0c0-9c6a-11ed-9f2e-5f9c6f2a70a0
if isfile(mesh_file)
    begin
        # Calculate element areas
        element_areas = Float64[]
        element_centers_x = Float64[]
        element_centers_y = Float64[]

        for el in 1:mesh.n_elements
            corners = mesh.corners[:, mesh.element_node_ids[:, el]]

            # Approximate area using shoelace formula for quadrilateral
            x = corners[1, :]
            y = corners[2, :]
            area = 0.5 * abs(
                x[1]*(y[2]-y[4]) + x[2]*(y[3]-y[1]) +
                x[3]*(y[4]-y[2]) + x[4]*(y[1]-y[3])
            )
            push!(element_areas, area)

            # Element center
            push!(element_centers_x, mean(x))
            push!(element_centers_y, mean(y))
        end

        fig2 = Figure(resolution=(1200, 500))

        # Spatial distribution of element size
        ax1 = Axis(fig2[1, 1],
            xlabel="X (m)",
            ylabel="Y (m)",
            title="Element Size Distribution (Area)",
            aspect=DataAspect()
        )

        scatter!(ax1, element_centers_x, element_centers_y,
            color=element_areas,
            colormap=:viridis,
            markersize=8,
            colorrange=(minimum(element_areas), maximum(element_areas))
        )
        Colorbar(fig2[1, 2], limits=(minimum(element_areas), maximum(element_areas)),
            colormap=:viridis, label="Element Area (m²)")

        # Histogram of element sizes
        ax2 = Axis(fig2[1, 3],
            xlabel="Element Area (m²)",
            ylabel="Count",
            title="Element Size Histogram"
        )
        hist!(ax2, element_areas, bins=30, color=:steelblue)

        fig2
    end
end

# ╔═╡ 90b0c0d0-9c6a-11ed-0f3e-6f0c7f3a81b0
md"""
## Mesh Quality Metrics

Statistics about mesh quality and distribution.
"""

# ╔═╡ a0c0d0e0-9c6a-11ed-1f4e-7f1c8f4a92c0
if isfile(mesh_file)
    begin
        min_area = minimum(element_areas)
        max_area = maximum(element_areas)
        mean_area = mean(element_areas)

        md"""
        **Element Area Statistics:**
        - Minimum: $(round(min_area, digits=1)) m²
        - Maximum: $(round(max_area, digits=1)) m²
        - Mean: $(round(mean_area, digits=1)) m²
        - Refinement ratio: $(round(max_area/min_area, digits=2))

        **Mesh Resolution:**
        - Finest element size: ~$(round(sqrt(min_area), digits=1)) m
        - Coarsest element size: ~$(round(sqrt(max_area), digits=1)) m
        """
    end
end

# ╔═╡ Cell order:
# ╠═8e9a3c40-9c6a-11ed-1f4e-7d1c8f4a9b2c
# ╟─1a2b3c4d-9c6a-11ed-2f5e-8d2c9f5a0b3d
# ╟─2b3c4d5e-9c6a-11ed-3f6e-9d3c0f6a1c4e
# ╠═3c4d5e6f-9c6a-11ed-4f7e-0d4c1f7a2d5f
# ╠═4d5e6f70-9c6a-11ed-5f8e-1d5c2f8a3e60
# ╟─5e6f7080-9c6a-11ed-6f9e-2e6c3f9a4f70
# ╠═6f708090-9c6a-11ed-7f0e-3f7c4f0a5880
# ╟─7080a0b0-9c6a-11ed-8f1e-4f8c5f1a6990
# ╠═80a0b0c0-9c6a-11ed-9f2e-5f9c6f2a70a0
# ╟─90b0c0d0-9c6a-11ed-0f3e-6f0c7f3a81b0
# ╟─a0c0d0e0-9c6a-11ed-1f4e-7f1c8f4a92c0
